/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 28 11:26:46 GMT 2024
 */

package com.dilizity.dynamicDAL;

import org.junit.Test;
import static org.junit.Assert.*;
import com.dilizity.dynamicDAL.Param;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Param_ESTest extends Param_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Param param0 = new Param();
      param0.setType("1ut9|wdTl.>H%m");
      String string0 = param0.getType();
      assertEquals("1ut9|wdTl.>H%m", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Param param0 = new Param();
      param0.setType("");
      String string0 = param0.getType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Param param0 = new Param();
      param0.setSize("n|'G\"'qo>AQ>vv");
      String string0 = param0.getSize();
      assertEquals("n|'G\"'qo>AQ>vv", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Param param0 = new Param();
      param0.setSize("");
      String string0 = param0.getSize();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Param param0 = new Param();
      param0.setOrder("n|'G\"'qo>AQ>vv");
      String string0 = param0.getOrder();
      assertEquals("n|'G\"'qo>AQ>vv", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Param param0 = new Param();
      param0.setName("uCW5HF<U?]W");
      String string0 = param0.getName();
      assertEquals("uCW5HF<U?]W", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Param param0 = new Param();
      param0.setName("");
      String string0 = param0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Param param0 = new Param();
      String string0 = param0.getOrder();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Param param0 = new Param();
      param0.setOrder("");
      String string0 = param0.getOrder();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Param param0 = new Param();
      String string0 = param0.getSize();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Param param0 = new Param();
      String string0 = param0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Param param0 = new Param();
      String string0 = param0.getType();
      assertNull(string0);
  }
}
