/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 28 11:21:10 GMT 2024
 */

package com.dilizity.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.dilizity.util.PropertiesWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PropertiesWrapper_ESTest extends PropertiesWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PropertiesWrapper propertiesWrapper0 = PropertiesWrapper.getInstance();
      String string0 = propertiesWrapper0.getProperty("", (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PropertiesWrapper propertiesWrapper0 = PropertiesWrapper.getInstance();
      String string0 = propertiesWrapper0.getProperty("config.properties", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PropertiesWrapper propertiesWrapper0 = PropertiesWrapper.getInstance();
      // Undeclared exception!
      try { 
        propertiesWrapper0.getProperty((String) null, "&Tv^k0Wl; lZHYlc/");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PropertiesWrapper propertiesWrapper0 = PropertiesWrapper.getInstance();
      // Undeclared exception!
      try { 
        propertiesWrapper0.getProperty((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        PropertiesWrapper.getInstance((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PropertiesWrapper propertiesWrapper0 = PropertiesWrapper.getInstance("Zom.core.util.ProprtiesWrapper");
      PropertiesWrapper propertiesWrapper1 = PropertiesWrapper.getInstance();
      assertSame(propertiesWrapper1, propertiesWrapper0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PropertiesWrapper propertiesWrapper0 = PropertiesWrapper.getInstance();
      PropertiesWrapper propertiesWrapper1 = PropertiesWrapper.getInstance("");
      assertSame(propertiesWrapper1, propertiesWrapper0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      PropertiesWrapper propertiesWrapper0 = PropertiesWrapper.getInstance();
      assertNotNull(propertiesWrapper0);
      
      String string0 = propertiesWrapper0.getProperty("", "^257)f\">_T\"");
      assertEquals("^257)f\">_T\"", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PropertiesWrapper propertiesWrapper0 = PropertiesWrapper.getInstance("Zom.core.util.ProprtiesWrapper");
      String string0 = propertiesWrapper0.getProperty("Zom.core.util.ProprtiesWrapper");
      assertNull(string0);
  }
}
