/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 28 11:26:35 GMT 2024
 */

package com.dilizity.dynamicDAL;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.dilizity.dynamicDAL.DynamicPOJO;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DynamicPOJO_ESTest extends DynamicPOJO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DynamicPOJO dynamicPOJO0 = new DynamicPOJO();
      dynamicPOJO0.properties = null;
      // Undeclared exception!
      try { 
        dynamicPOJO0.setProperties("a(^T7L@eqBeWN0]7:", "a(^T7L@eqBeWN0]7:");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.core.dynamicDAL.DynamicPOJO", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DynamicPOJO dynamicPOJO0 = new DynamicPOJO();
      // Undeclared exception!
      try { 
        dynamicPOJO0.getProperties((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DynamicPOJO dynamicPOJO0 = new DynamicPOJO();
      Integer integer0 = new Integer(3002);
      dynamicPOJO0.setProperties("", integer0);
      Object object0 = dynamicPOJO0.getProperties("");
      assertEquals(3002, object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DynamicPOJO dynamicPOJO0 = new DynamicPOJO();
      Object object0 = dynamicPOJO0.getProperties("");
      assertNull(object0);
  }
}
